package net.chrisrichardson.bankingExample.infrastructure;

import org.springframework.jdbc.core.JdbcTemplate;

public class SchemaCreator {

  private static String[] ddl = {
      "create table BANKING_TRANSACTION (id integer generated by default as identity (start with 1), fromAccount integer, toAccount integer, amount double, date timestamp, primary key (id))",
      "create table BANK_ACCOUNT (ACCOUNT_ID integer generated by default as identity (start with 1), BALANCE double, accountId varchar(255), overdraftPolicy integer, dateOpened timestamp, requiredYearsOpen double, limit double, primary key (ACCOUNT_ID))",
      "alter table BANKING_TRANSACTION add constraint FKAD190052A8B6B92 foreign key (toAccount) references BANK_ACCOUNT",
      "alter table BANKING_TRANSACTION add constraint FKAD1900591467F83 foreign key (fromAccount) references BANK_ACCOUNT" };

  private final JdbcTemplate jdbcTemplate;

  public SchemaCreator(JdbcTemplate jdbcTemplate) {
    this.jdbcTemplate = jdbcTemplate;
    if (!schemaExists())
      createSchema();
  }

  private boolean schemaExists() {
    try {
      jdbcTemplate.execute("SELECT * FROM BANKING_TRANSACTION");
      return true;
    } catch (Exception e) {
      return false;
    }
  }

  private void createSchema() {
    for (String statement : ddl) {
      jdbcTemplate.execute(statement);
    }
  }

}
